### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (20,20) (2,) 

### ISSUE THREAD

**Issue by MonsterLaplace** [mariemorel/condor#7]
**When I run the test data, somthing wrong with this problem. Is there any solutions to solve this problems ? Thank you!**
pastml:ERROR:01:00:56 Frequencies given in parameters ([0.059954 0.055887]) do not sum up to one (0.115841),ignoring them.
Traceback (most recent call last):
  File "/mnt/z/xb/miniconda3/envs/nextflow/bin/pastml", line 8, in <module>
    sys.exit(main())
  File "/mnt/z/xb/miniconda3/envs/nextflow/lib/python3.10/site-packages/pastml/acr.py", line 1107, in main
    pastml_pipeline(**vars(params))
  File "/mnt/z/xb/miniconda3/envs/nextflow/lib/python3.10/site-packages/pastml/acr.py", line 532, in pastml_pipeline
    acr_results = acr(forest=roots, columns=columns, column2states=column2states,
  File "/mnt/z/xb/miniconda3/envs/nextflow/lib/python3.10/site-packages/pastml/acr.py", line 202, in acr
    model_instance = model2class[model](parameter_file=params, rate_matrix_file=rate_file, reoptimise=reoptimise,
  File "/mnt/z/xb/miniconda3/envs/nextflow/lib/python3.10/site-packages/pastml/models/CustomRatesModel.py", line 52, in __init__
    self.D_DIAGONAL, self.A, self.A_INV = get_diagonalisation(self.frequencies, self._rate_matrix)
  File "/mnt/z/xb/miniconda3/envs/nextflow/lib/python3.10/site-packages/pastml/models/generator.py", line 28, in get_diagonalisation
    Q = get_normalised_generator(frequencies, rate_matrix)
  File "/mnt/z/xb/miniconda3/envs/nextflow/lib/python3.10/site-packages/pastml/models/generator.py", line 47, in get_normalised_generator
    generator = rate_matrix * frequencies
ValueError: operands could not be broadcast together with shapes (20,20) (2,)

**Comment by fredericlemoine** [comment]
Hi, 
In order to reproduce the issue, can you give the exact command line you executed please?
Thank you

**Comment by MonsterLaplace** [comment]
> Hi, In order to reproduce the issue, can you give the exact command line you executed please? Thank you
Thank you for your quick response.
The command line i used is the same as which you displayed in the CONDOR program release page.
When I downgrade the python version from 3.10 to 3.7.3, problem solved,. Test data was run successfuly. I guess the problem was the lateat version of  numpy in python 3.10 . My own data is still running. If other problem  happened, I will leave a message here in the near future.

**Comment by fredericlemoine** [comment]
Ok, thank you for the feedback.
Do not hesitate if you have other problems.
